# Site settings
title: Partially Derivative
description: The data of the world around us
baseurl: # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lorem Ipsum
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: Partially Derivative
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: podcast
    url: /podcast
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# Podcast settings
podcast_url: http://www.partiallyderivative.com
podcast_album_art: /assets/logos/cover170x170.jpeg
podcast_title: Partially Derivative
podcast_owner: Partially Derivative
podcast_email: hello@partiallyderivative.com
podcast_category: Technology
podcast_subcategory_one: IT News
podcast_subcategory_two: Software How-To
podcast_explicit: "yes"
podcast_author: Vidya Spandana, Jonathon Morgan, and Chris Albon
podcast_description: The data of the world around us, hosted by data science super geeks. For the nerdy and nerd curious.
podcast_summary: Partially Derivative is a weekly podcast from the founders of Popily. We geek out about silly data stories, interview fun people doing interesting work, and drink beer.
podcast_subtitle: A podcast about the data of everything.
